make route for become-a-provider
frequency-chain/provider-dashboard pull request #188
Opened 2024-10-29 23:18 UTC by shannonwells

## Goal
The goal of this PR is to make a route for become-a-provider so that it's easier to navigate between the login/become provider routes

Closes #183 

## Discussion

## Checklist

- [ ] PR Self-Review and Commenting
- [ ] Tests added

## How To Test the Changes
```shell
git fetch && git co feat/link-become-provider-#183
npm install
npm run dev
```
1. Verify that after clicking 'Become a Provider' from the main page:
  a. the browser back button takes you back home.
  b. the 'Back' link takes you back home.
  c. ... and selecting Testnet network, the 'Cancel' link takes you back home.
  d. ... and selecting Mainnet network, the 'Cancel' link takes you back home.
3. Verify that clicking  'Home' also takes you home even if you have connected.  If logged in, you should see the dashboard.  If not, you should see the Connect and Become A Provider elements

2024-10-31 22:00 UTC, shannonwells commented on src/routes/+page.svelte
>    <ProviderLogin />
Since it's just a link now we don't need 3 conditions.

2024-10-31 22:03 UTC, shannonwells commented on test/unit-and-integration/createProvider.test.ts
> -  const mockCancelAction = vi.fn();
cancelActionsand mockCancelActions all went away because now you just go back to root, as a link.

2024-11-01 21:11 UTC, JoeCap08055 requested changes
Update `Testing` section of README with instructions to install necessary Playwright browsers before running tests

2024-11-04 15:17 UTC, JoeCap08055 approved these changes
- Reviewed code
- Pulled branch, ran tests & browsed locally

2024-11-04 17:53 UTC, merged